repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        name: Format Package

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        name: Lint Package

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.5.0
    hooks:
      - id: seed-isort-config
        name: Propogate Third-Party Packages

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
        name: Sort Package Imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.641
    hooks:
      - id: mypy
        name: Typecheck Package
